import Switch from "@mui/material/Switch";
import { HiOutlineArrowRight, HiOutlineBolt, HiOutlineCheckCircle, HiOutlineCircleStack, HiOutlineClock, HiOutlineCpuChip, HiOutlineExclamationTriangle, HiOutlineServerStack, HiOutlineShieldCheck, HiOutlineSparkles } from "react-icons/hi2";
import AIEntityCrud, { AIEntityCardActions } from "@/components/dashboard/AIEntityCrud";
import AITokenInsights from "@/components/dashboard/AITokenInsights";
import { useAIManagement } from "./AIManagementContext";

const colors=["var(--primary)","var(--success)","var(--warning)","var(--danger)"];
const compact=(n=0)=>n>=1e6?`${(n/1e6).toFixed(1)}M`:n>=1e3?`${(n/1e3).toFixed(1)}K`:String(n);
const nameOf=(v:any)=>v?.displayName||v?.name||v?.externalId||"Unknown";
const statusClass=(s="")=>["success","healthy","active","online","configured","enabled"].includes(s)?"bg-success/10 text-success":["failed","offline","disabled","missing env"].includes(s)?"bg-danger/10 text-danger":"bg-warning/10 text-warning";
const Badge=({value}:{value:string})=><span className={`rounded px-2 py-1 text-[9px] font-black uppercase ${statusClass(value)}`}>{value}</span>;
const Stat=({label,value}:any)=><div className="rounded-lg bg-surface-muted/70 px-3 py-2"><span className="block text-[9px] font-black uppercase text-muted-foreground">{label}</span><strong className="text-xs">{value}</strong></div>;
const Icon=({children}:any)=><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-primary/10 text-primary">{children}</span>;
const Card=({children,color=colors[0]}:any)=><article className="overflow-hidden rounded-xl border border-border bg-surface-elevated shadow-sm transition hover:-translate-y-0.5 hover:border-primary/50"><i className="block h-1" style={{background:color}}/><div className="p-3.5">{children}</div></article>;
const Crud=({kind,items}:any)=>{const ctx=useAIManagement();return <AIEntityCrud kind={kind} items={items} providers={ctx.providers} models={ctx.models} agents={ctx.agents} workspace={ctx.workspace} onChanged={()=>void ctx.reload()}/>};

export function OverviewView(){const {overview,analytics,agents,providers}=useAIManagement();if(!overview)return null;const metrics=[["Requests",compact(overview.requests),<HiOutlineBolt/>],["Success",`${overview.success_rate}%`,<HiOutlineCheckCircle/>],["Tokens",compact(overview.total_tokens),<HiOutlineCircleStack/>],["Latency",`${overview.average_latency_ms}ms`,<HiOutlineClock/>],["Agents",overview.agents,<HiOutlineSparkles/>],["Providers",overview.providers,<HiOutlineServerStack/>]];const max=Math.max(1,...analytics.daily.map((d:any)=>d.requests));return <div className="space-y-4"><div className="grid grid-cols-2 gap-2 lg:grid-cols-6">{metrics.map(([label,value,icon])=><div key={String(label)} className="flex items-center justify-between rounded-xl border border-border bg-surface-elevated px-3.5 py-2.5"><div><span className="block text-[9px] font-black uppercase text-muted-foreground">{label}</span><strong>{value}</strong></div><span className="text-primary">{icon}</span></div>)}</div><div className="grid gap-3 lg:grid-cols-[2fr_1fr]"><section className="rounded-xl border border-border bg-card p-4"><h2 className="m-0 text-xs font-black uppercase">30-day request velocity</h2><div className="mt-4 flex h-44 items-end gap-1">{analytics.daily.map((d:any)=><i key={d._id} title={`${d._id}: ${d.requests}`} className="min-w-1 flex-1 rounded-t bg-primary/70 hover:bg-primary" style={{height:`${Math.max(3,d.requests/max*100)}%`}}/>)}</div></section><section className="rounded-xl border border-border bg-card p-4"><h2 className="m-0 text-xs font-black uppercase">Live fleet</h2>{agents.slice(0,5).map((a:any)=><div key={a._id} className="mt-3 flex items-center gap-2 text-xs"><i className="h-2 w-2 rounded-full bg-success"/><b className="flex-1">{a.name}</b><span className="text-[9px] text-muted-foreground">{nameOf(a.primaryModelId)}</span></div>)}<h2 className="mb-0 mt-5 text-xs font-black uppercase">Provider health</h2>{providers.slice(0,4).map(p=><div key={p.id} className="mt-2 flex justify-between text-xs"><b>{p.name}</b><Badge value={p.health}/></div>)}</section></div></div>}

export function ProvidersView(){const c=useAIManagement();return <div className="space-y-3"><div className="text-xs text-muted-foreground">Providers are registry-managed. Configure, enable and prioritize them here.</div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{c.filter(c.providers).map((p,i)=><Card key={p.id} color={colors[i%colors.length]}><div className="flex justify-between"><Icon><HiOutlineServerStack/></Icon><Switch checked={p.enabled} onChange={()=>void c.toggleProvider(p)}/></div><h3 className="mb-1 mt-3 text-sm font-black">{p.name}</h3><code className="text-[9px] text-muted-foreground">{p.code}</code><div className="mt-3 flex gap-2"><Badge value={p.configured?"configured":"missing env"}/><Badge value={p.health}/></div></Card>)}</div></div>}

export function ModelsView(){const c=useAIManagement(),items=c.filter(c.models);return <div className="space-y-3"><Crud kind="Models" items={items}/><div className="flex flex-wrap gap-3">{items.map((m:any,i:number)=><div key={m._id} className="min-w-[180px] max-w-[260px] flex-1"><Card color={colors[i%colors.length]}><div className="flex justify-between"><Icon><HiOutlineCpuChip/></Icon><div className="flex items-center"><Badge value={m.enabled?"enabled":"disabled"}/><AIEntityCardActions kind="Models" item={m}/></div></div><h3 className="mb-1 mt-3 truncate text-sm font-black">{nameOf(m)}</h3><p className="m-0 text-[10px] text-muted-foreground">{m.providerId?.name}</p><div className="mt-3 grid grid-cols-2 gap-2"><Stat label="Context" value={compact(m.contextWindow)}/><Stat label="Output" value={compact(m.maxOutputTokens)}/></div></Card></div>)}</div></div>}

export function AgentsView(){const c=useAIManagement(),items=c.filter(c.agents);return <div className="space-y-3"><Crud kind="Agents" items={items}/><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{items.map((a:any,i:number)=><Card key={a._id} color={colors[i%colors.length]}><div className="flex justify-between"><Icon><HiOutlineSparkles/></Icon><div className="flex items-center"><Badge value={a.enabled?"online":"offline"}/><AIEntityCardActions kind="Agents" item={a}/></div></div><h3 className="mb-1 mt-3 text-sm font-black">{a.name}</h3><p className="line-clamp-2 text-[10px] text-muted-foreground">{a.description}</p><div className="flex justify-between rounded-lg bg-surface-muted p-2 text-[10px]"><span><HiOutlineShieldCheck className="inline text-success"/> {a.securityRoleId?.name}</span><b>{nameOf(a.primaryModelId)}</b></div></Card>)}</div></div>}

export function RoutingView(){const c=useAIManagement(),items=c.filter(c.routing);return <div className="space-y-3"><Crud kind="Routing" items={items}/><div className="grid gap-3 xl:grid-cols-2">{items.map((r:any,i:number)=><Card key={r._id} color={colors[i%colors.length]}><div className="flex justify-between"><div><span className="text-[9px] font-black uppercase text-primary">{String(r.strategy).replace("_"," ")}</span><h3 className="m-0 text-sm font-black">{r.name}</h3></div><div className="flex items-center"><Badge value={r.enabled?"active":"disabled"}/><AIEntityCardActions kind="Routing" item={r}/></div></div><div className="mt-3 flex flex-wrap items-center gap-2"><Node label="Agent" value={nameOf(r.agentId)} icon={<HiOutlineSparkles/>}/><HiOutlineArrowRight className="text-primary"/><div className="flex min-w-[100px] flex-1 flex-wrap gap-2">{r.modelIds?.map((m:any,x:number)=><Node key={m._id} label={x?`Fallback ${x}`:"Primary"} value={nameOf(m)} icon={<HiOutlineCpuChip/>}/>)}</div></div><div className="mt-2 grid grid-cols-2 gap-2"><Stat label="Retries" value={r.maxRetries}/><Stat label="Timeout" value={`${r.timeoutMs}ms`}/></div></Card>)}</div></div>}
const Node=({label,value,icon}:any)=><div className="min-w-[100px] max-w-[150px] flex-1 rounded-lg border border-border bg-surface-muted/50 p-2"><span className="flex gap-1 text-[8px] font-black uppercase text-primary">{icon}{label}</span><b className="block truncate text-[10px]">{value}</b></div>;

export function QuotasView(){const c=useAIManagement(),items=c.filter(c.quotas);return <div className="space-y-3"><AITokenInsights workspace={c.workspace} mode="quota"/><Crud kind="Quotas" items={items}/><section className="overflow-hidden rounded-xl border border-border bg-card">{items.map((q:any)=>{const pct=q.tokenLimit?Math.round(q.usedTokens/q.tokenLimit*100):0;return <div key={q._id} className="grid grid-cols-[1.1fr_.65fr_1fr_.7fr_auto] items-center gap-3 border-b border-border px-4 py-3 last:border-0"><div><b className="block text-xs">{q.name}</b><span className="text-[9px] text-muted-foreground">{q.period}</span></div><Badge value={q.enabled?"active":"disabled"}/><div><div className="flex justify-between text-[9px]"><span>{compact(q.usedTokens)} tokens</span><b>{pct}%</b></div><div className="mt-1 h-1.5 rounded bg-surface-muted"><i className="block h-full rounded bg-primary" style={{width:`${Math.min(100,pct)}%`}}/></div></div><span className="text-[10px]">{compact(q.tokenLimit)} limit</span><AIEntityCardActions kind="Quotas" item={q}/></div>})}</section></div>}

export function AnalyticsView(){const c=useAIManagement();return <div className="space-y-4"><AITokenInsights workspace={c.workspace} mode="analytics"/><section className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{c.analytics.providers.map((p:any)=><div key={p._id} className="rounded-xl border border-border bg-card p-3"><div className="flex justify-between"><b className="capitalize">{p._id}</b><span className="text-xs text-primary">{p.requests} req</span></div><div className="mt-2 grid grid-cols-3 gap-2"><Stat label="Tokens" value={compact(p.tokens)}/><Stat label="Latency" value={`${Math.round(p.avgLatencyMs)}ms`}/><Stat label="Cost" value={`$${p.costUsd.toFixed(3)}`}/></div></div>)}</section></div>}

export function RequestLogsView(){const c=useAIManagement(),items=c.filter(c.logs);return <div className="space-y-3"><AITokenInsights workspace={c.workspace} mode="logs"/><section className="overflow-hidden rounded-xl border border-border bg-card"><header className="flex justify-between border-b border-border bg-surface-muted px-4 py-2 text-[10px] font-black uppercase"><span>Live execution telemetry</span><span>{items.length} records</span></header><div className="max-h-[580px] overflow-auto">{items.map((l:any)=><div key={l._id} className="grid grid-cols-[32px_1.2fr_1fr_.5fr_.5fr_.5fr] items-center gap-3 border-b border-border px-4 py-2.5 text-xs"><Icon>{l.status==="failed"?<HiOutlineExclamationTriangle/>:<HiOutlineBolt/>}</Icon><div><b className="block capitalize">{l.provider}</b><span className="text-[9px] text-muted-foreground">{l.model}</span></div><span className="text-[9px]">{new Date(l.createdAt).toLocaleString()}</span><b>{compact(l.totalTokens)}</b><span>{l.latencyMs}ms</span><Badge value={l.status}/></div>)}</div></section></div>}
