import { HiOutlineBolt, HiOutlineCheckCircle, HiOutlineCircleStack, HiOutlineClock, HiOutlineCpuChip, HiOutlineExclamationTriangle, HiOutlineQueueList, HiOutlineServerStack, HiOutlineSparkles } from "react-icons/hi2";
import AITokenInsights from "@/components/dashboard/AITokenInsights";
import { useAIManagement } from "../AIManagementContext";

const compact=(n=0)=>n>=1e6?`${(n/1e6).toFixed(1)}M`:n>=1e3?`${(n/1e3).toFixed(1)}K`:String(n);
const nameOf=(value:any)=>value?.displayName||value?.name||value?.externalId||"Unknown";
const statusClass=(status="")=>["success","healthy","active","online","configured","enabled"].includes(status)?"bg-success/10 text-success":["failed","offline","disabled","missing env"].includes(status)?"bg-danger/10 text-danger":"bg-warning/10 text-warning";
const Badge=({value}:{value:string})=><span className={`rounded px-2 py-1 text-[8px] font-black uppercase ${statusClass(value)}`}>{value}</span>;
const Metric=({label,value,detail,icon}:any)=><article className="flex min-w-0 items-center justify-between rounded-xl border border-border bg-surface-elevated px-3.5 py-2.5 shadow-sm"><div className="min-w-0"><span className="block truncate text-[9px] font-black uppercase text-muted-foreground">{label}</span><strong className="block text-base font-black">{value}</strong>{detail&&<small className="block truncate text-[8px] text-muted-foreground">{detail}</small>}</div><span className="ml-2 text-lg text-primary">{icon}</span></article>;
const Panel=({title,subtitle,children,className=""}:any)=><section className={`rounded-xl border border-border bg-card p-4 shadow-sm ${className}`}><header><h2 className="m-0 text-xs font-black uppercase tracking-wide">{title}</h2><p className="mb-0 mt-0.5 text-[9px] text-muted-foreground">{subtitle}</p></header>{children}</section>;

export default function OverviewView(){
 const c=useAIManagement();const o=c.overview;if(!o)return null;
 const maxDaily=Math.max(1,...c.analytics.daily.map((d:any)=>d.requests));const totalStatuses=c.analytics.statuses.reduce((n:number,s:any)=>n+s.count,0);
 const failed=c.analytics.statuses.find((s:any)=>s._id==="failed")?.count||0;const quotaRisk=c.quotas.filter((q:any)=>q.tokenLimit&&q.usedTokens/q.tokenLimit>=.7).length;
 return <div className="space-y-4">
  <section className="grid grid-cols-2 gap-2 md:grid-cols-4 xl:grid-cols-8">
   <Metric label="AI requests" value={compact(o.requests)} detail="All executions" icon={<HiOutlineBolt/>}/><Metric label="Success rate" value={`${o.success_rate}%`} detail={`${failed} failed`} icon={<HiOutlineCheckCircle/>}/><Metric label="Tokens" value={compact(o.total_tokens)} detail="AI request logs" icon={<HiOutlineCircleStack/>}/><Metric label="Avg latency" value={`${o.average_latency_ms}ms`} detail="Response time" icon={<HiOutlineClock/>}/><Metric label="Agents" value={o.agents} detail="Workspace fleet" icon={<HiOutlineSparkles/>}/><Metric label="Models" value={o.models} detail="Available engines" icon={<HiOutlineCpuChip/>}/><Metric label="Providers" value={o.providers} detail="Connected network" icon={<HiOutlineServerStack/>}/><Metric label="Quota risk" value={quotaRisk} detail="Above 70%" icon={<HiOutlineExclamationTriangle/>}/>
  </section>
  <AITokenInsights workspace={c.workspace} mode="analytics"/>
  <section className="grid gap-4 xl:grid-cols-[2fr_1fr]">
   <Panel title="AI request velocity" subtitle="Requests and failures across the last 30 days"><div className="mt-4 flex h-52 items-end gap-1 border-b border-border">{c.analytics.daily.map((day:any)=><div key={day._id} className="group relative flex h-full min-w-1 flex-1 items-end"><i className="block w-full rounded-t bg-primary/70 transition hover:bg-primary" style={{height:`${Math.max(3,day.requests/maxDaily*100)}%`}}/><span className="absolute bottom-full left-1/2 z-10 mb-1 hidden -translate-x-1/2 whitespace-nowrap rounded bg-foreground px-2 py-1 text-[8px] text-background group-hover:block">{day._id}: {day.requests} requests · {day.failures} failed</span></div>)}</div></Panel>
   <Panel title="Execution outcomes" subtitle="Reliability distribution for AI traffic"><div className="mt-5 grid grid-cols-[130px_1fr] items-center gap-5"><div className="grid h-32 w-32 place-items-center rounded-full" style={{background:`conic-gradient(var(--success) 0 ${totalStatuses?(totalStatuses-failed)/totalStatuses*100:0}%, var(--danger) 0 100%)`}}><div className="grid h-24 w-24 place-items-center rounded-full bg-card text-center"><div><strong className="block text-xl">{compact(totalStatuses)}</strong><span className="text-[8px] uppercase text-muted-foreground">Executions</span></div></div></div><div>{c.analytics.statuses.map((status:any)=><div key={status._id} className="mb-2 flex items-center justify-between text-[10px]"><Badge value={status._id}/><b>{status.count}</b></div>)}</div></div></Panel>
  </section>
  <section className="grid gap-4 lg:grid-cols-2 xl:grid-cols-3">
   <Panel title="Provider performance" subtitle="Traffic, cost and upstream latency" className="xl:col-span-2"><div className="mt-3 grid gap-2 md:grid-cols-2">{c.analytics.providers.map((provider:any)=><div key={provider._id} className="rounded-lg border border-border bg-surface-muted/30 p-3"><div className="flex justify-between"><b className="text-xs capitalize">{provider._id}</b><span className="text-[9px] text-primary">{provider.requests} requests</span></div><div className="mt-2 grid grid-cols-3 text-[9px]"><span>{compact(provider.tokens)} tokens</span><span>{Math.round(provider.avgLatencyMs)}ms</span><b className="text-right">${provider.costUsd.toFixed(3)}</b></div></div>)}</div></Panel>
   <Panel title="Agent fleet" subtitle="Roles and assigned primary models"><div className="mt-2">{c.agents.slice(0,6).map((agent:any)=><div key={agent._id} className="flex items-center gap-2 border-b border-border py-2 last:border-0"><span className={`h-2 w-2 rounded-full ${agent.enabled?"bg-success":"bg-muted"}`}/><div className="min-w-0 flex-1"><b className="block truncate text-[10px]">{agent.name}</b><span className="block truncate text-[8px] text-muted-foreground">{agent.securityRoleId?.name}</span></div><span className="max-w-28 truncate text-[8px] text-primary">{nameOf(agent.primaryModelId)}</span></div>)}</div></Panel>
   <Panel title="Routing control" subtitle="Active policies and fallback depth"><div className="mt-2">{c.routing.slice(0,6).map((route:any)=><div key={route._id} className="flex items-center gap-2 border-b border-border py-2 last:border-0"><HiOutlineQueueList className="text-primary"/><div className="min-w-0 flex-1"><b className="block truncate text-[10px]">{route.name}</b><span className="text-[8px] capitalize text-muted-foreground">{String(route.strategy).replace("_"," ")}</span></div><Badge value={route.enabled?"active":"disabled"}/><b className="text-[9px]">{route.modelIds?.length||0} models</b></div>)}</div></Panel>
   <Panel title="Quota posture" subtitle="Budgets closest to their configured limit"><div className="mt-3 space-y-3">{[...c.quotas].sort((a:any,b:any)=>(b.usedTokens/b.tokenLimit)-(a.usedTokens/a.tokenLimit)).slice(0,5).map((quota:any)=>{const pct=quota.tokenLimit?Math.min(100,Math.round(quota.usedTokens/quota.tokenLimit*100)):0;return <div key={quota._id}><div className="mb-1 flex justify-between text-[9px]"><b>{quota.name}</b><span>{pct}% · {compact(quota.usedTokens)}</span></div><div className="h-1.5 rounded bg-surface-muted"><i className={`block h-full rounded ${pct>=90?"bg-danger":pct>=70?"bg-warning":"bg-primary"}`} style={{width:`${pct}%`}}/></div></div>})}</div></Panel>
   <Panel title="Recent AI executions" subtitle="Latest model activity and failures"><div className="mt-2">{c.logs.slice(0,6).map((log:any)=><div key={log._id} className="grid grid-cols-[8px_1fr_auto] items-center gap-2 border-b border-border py-2 last:border-0"><i className={`h-2 w-2 rounded-full ${log.status==="failed"?"bg-danger":log.status==="fallback"?"bg-warning":"bg-success"}`}/><div className="min-w-0"><b className="block truncate text-[10px] capitalize">{log.provider} / {log.model}</b><span className="text-[8px] text-muted-foreground">{new Date(log.createdAt).toLocaleString()}</span></div><div className="text-right"><b className="block text-[9px]">{compact(log.totalTokens)} tokens</b><span className="text-[8px] text-muted-foreground">{log.latencyMs}ms</span></div></div>)}</div></Panel>
  </section>
 </div>;
}
