import CircularProgress from "@mui/material/CircularProgress";
import { useEffect, useState } from "react";
import { HiOutlineBolt, HiOutlineCircleStack, HiOutlineCurrencyDollar, HiOutlineGlobeAlt } from "react-icons/hi2";
import { fetchTokenAnalytics, type TokenAnalyticsData } from "@/services/llms/tokens";

const compact=(n=0)=>n>=1e6?`${(n/1e6).toFixed(1)}M`:n>=1e3?`${(n/1e3).toFixed(1)}K`:String(n);
const Metric=({label,value,icon}:any)=><div className="flex items-center justify-between rounded-xl border border-border bg-surface-elevated px-3.5 py-2.5 shadow-sm"><div><span className="block text-[9px] font-black uppercase text-muted-foreground">{label}</span><strong className="text-base font-black">{value}</strong></div><span className="text-lg text-primary">{icon}</span></div>;

export default function AITokenInsights({workspace,mode}:{workspace?:string;mode:"analytics"|"quota"|"logs"}){
 const [data,setData]=useState<TokenAnalyticsData|null>(null);
 useEffect(()=>{let live=true;fetchTokenAnalytics(workspace).then(v=>{if(live)setData(v)}).catch(()=>{});return()=>{live=false}},[workspace]);
 if(!data)return <div className="flex h-16 items-center justify-center"><CircularProgress size={20}/></div>;
 const total=data.overall_totals,perf=data.performance_metrics,external=data.external_vs_internal.external_api,internal=data.external_vs_internal.internal_agent;
 if(mode==="quota")return <section className="grid grid-cols-2 gap-2 lg:grid-cols-4"><Metric label="Tracked tokens" value={compact(total.grand_total_all)} icon={<HiOutlineCircleStack/>}/><Metric label="Estimated spend" value={`$${total.total_cost_usd.toFixed(3)}`} icon={<HiOutlineCurrencyDollar/>}/><Metric label="Cost / 1K" value={`$${perf.costPerThousand.toFixed(4)}`} icon={<HiOutlineBolt/>}/><Metric label="Requests" value={compact(total.grand_total_requests)} icon={<HiOutlineGlobeAlt/>}/></section>;
 if(mode==="logs")return <section className="overflow-hidden rounded-xl border border-border bg-card"><div className="border-b border-border bg-surface-muted px-4 py-2 text-[10px] font-black uppercase text-primary">API key telemetry included from Token Management</div><div className="flex flex-wrap gap-2 p-3">{Object.entries(data.metrics_per_api_key).map(([id,row])=><div key={id} className="min-w-[180px] flex-1 rounded-lg border border-border px-3 py-2"><div className="flex justify-between"><strong className="text-[10px]">{row.provider}</strong><span className="font-mono text-[9px] text-muted-foreground">{id.slice(0,12)}…</span></div><div className="mt-1 flex justify-between text-[10px]"><span>{compact(row.totals.total_tokens)} tokens</span><b>{row.totals.requests} requests</b></div></div>)}</div></section>;
 const max=Math.max(1,...data.model_cost_breakdown.map(x=>x.total_tokens));
 return <section className="space-y-3"><div className="grid grid-cols-2 gap-2 lg:grid-cols-5"><Metric label="All tokens" value={compact(total.grand_total_all)} icon={<HiOutlineCircleStack/>}/><Metric label="Input / output" value={`${compact(total.grand_total_input)} / ${compact(total.grand_total_output)}`} icon={<HiOutlineBolt/>}/><Metric label="Estimated cost" value={`$${total.total_cost_usd.toFixed(3)}`} icon={<HiOutlineCurrencyDollar/>}/><Metric label="Latency" value={`${perf.avgLatencyMs}ms`} icon={<HiOutlineBolt/>}/><Metric label="Generation" value={`${perf.avgTokensPerSec} t/s`} icon={<HiOutlineGlobeAlt/>}/></div><div className="grid gap-3 lg:grid-cols-[1fr_2fr]"><article className="rounded-xl border border-border bg-card p-4"><h3 className="m-0 text-xs font-black uppercase">Traffic sources</h3><div className="mt-4 flex h-3 overflow-hidden rounded-full bg-surface-muted"><i className="bg-primary" style={{width:`${total.grand_total_all?external.total/total.grand_total_all*100:0}%`}}/><i className="bg-success" style={{width:`${total.grand_total_all?internal.total/total.grand_total_all*100:0}%`}}/></div><div className="mt-3 flex justify-between text-[10px]"><span className="text-primary">External APIs · {compact(external.total)}</span><span className="text-success">Internal agents · {compact(internal.total)}</span></div></article><article className="rounded-xl border border-border bg-card p-4"><h3 className="m-0 text-xs font-black uppercase">Model cost & token distribution</h3><div className="mt-3 grid gap-2">{data.model_cost_breakdown.slice(0,6).map(row=><div key={`${row.provider}-${row.model}`} className="grid grid-cols-[minmax(120px,1fr)_2fr_auto] items-center gap-3 text-[10px]"><span className="truncate font-bold">{row.model}<small className="ml-1 text-muted-foreground">{row.provider}</small></span><div className="h-1.5 overflow-hidden rounded-full bg-surface-muted"><i className="block h-full rounded-full bg-primary" style={{width:`${row.total_tokens/max*100}%`}}/></div><b>${row.costUSD.toFixed(3)}</b></div>)}</div></article></div></section>;
}
